name: BoxLetter
main: fr.crocofabs.BoxLetter.BoxLetter
version: 0.0.1
author: CrocoFabs
commands:
    boxletter:
        usage: /boxletter [Player] /boxletter stop pour arreter.
permissions:
    boxletter:
        description: Permission pour BoxLetter.
        default: true